// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<ProcessResult> processImage({
  required List<int> jpeg,
  required int w,
  required int h,
  required int quality,
}) => RustLib.instance.api.crateApiImagePipelineProcessImage(
  jpeg: jpeg,
  w: w,
  h: h,
  quality: quality,
);

class ProcessResult {
  final Uint8List jpeg;
  final int decodeMs;
  final int processMs;
  final int encodeMs;

  const ProcessResult({
    required this.jpeg,
    required this.decodeMs,
    required this.processMs,
    required this.encodeMs,
  });

  @override
  int get hashCode =>
      jpeg.hashCode ^
      decodeMs.hashCode ^
      processMs.hashCode ^
      encodeMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProcessResult &&
          runtimeType == other.runtimeType &&
          jpeg == other.jpeg &&
          decodeMs == other.decodeMs &&
          processMs == other.processMs &&
          encodeMs == other.encodeMs;
}
